import 'package:flutter/material.dart';
import 'package:easy_localization/easy_localization.dart';

class AppConstants {
  // ДОДАНО: Єдиний список підтримуваних мов
  static const Map<String, String> languages = {
    'uk': 'Українська',
    'en': 'English',
    'de': 'Deutsch',
    'pl': 'Polski',
    'es': 'Español',
    'fr': 'Français',
    'it': 'Italiano',
    'pt': 'Português',
    'nl': 'Nederlands',
    'tr': 'Türkçe',
    'cs': 'Čeština',
    'ro': 'Română',
    'hu': 'Magyar',
    'sk': 'Slovenčina',
    'el': 'Ελληνικά',
    'bg': 'Български',
    'sv': 'Svenska',
    'da': 'Dansk',
    'fi': 'Suomi',
    'hr': 'Hrvatski',
    'zh': '简体中文',
    'id': 'Bahasa Indonesia',
    'ms': 'Bahasa Melayu',
    'vi': 'Tiếng Việt',
    'fil': 'Filipino',
    'hi': 'हिन्दी',
    'bn': 'বাংলা',
    'th': 'ไทย',
    'ja': '日本語',
    'ko': '한국어',
    'sw': 'Kiswahili',
    'az': 'Azərbaycan',
    'sq': 'Shqip',
    'bs': 'Bosanski',
    'sr': 'Српски',
    'mk': 'Македонски',
    'kk': 'Қазақ',
    'mn': 'Монгол',
    'hy': 'Հայերեն',
    'ka': 'ქართული',
    'ne': 'नेपाली',
    'am': 'አማርኛ',
    'si': 'සිංහල',
    'my': 'မြန်မာ',
    'km': 'ខ្មែរ',
    'lo': 'ລາວ',
    'ar': 'العربية',
    'fa': 'فارسی',
    'ur': 'اردو',
    'he': 'עברית',
  };

  // Використовуємо getter (get), щоб переклади підтягувалися динамічно
  static Map<String, List<IconData>> get groupedIcons => {
    'icons_finance'.tr(): [
      Icons.account_balance_wallet,
      Icons.wallet,
      Icons.account_balance,
      Icons.savings,
      Icons.credit_card,
      Icons.show_chart,
      Icons.candlestick_chart,
      Icons.pie_chart,
      Icons.trending_up,
      Icons.atm,
      Icons.percent,
      Icons.real_estate_agent,
      Icons.receipt_long,
      Icons.business_center,
      Icons.money,
    ],
    'icons_currencies'.tr(): [
      Icons.attach_money,
      Icons.euro,
      Icons.currency_pound,
      Icons.currency_yen,
      Icons.currency_franc,
      Icons.currency_lira,
      Icons.currency_rupee,
      Icons.currency_bitcoin,
      Icons.payments,
      Icons.price_change,
    ],
    'icons_food'.tr(): [
      Icons.shopping_bag,
      Icons.shopping_cart,
      Icons.restaurant,
      Icons.coffee,
      Icons.fastfood,
      Icons.local_bar,
      Icons.cake,
      Icons.local_pizza,
      Icons.liquor,
      Icons.icecream,
    ],
    'icons_transport'.tr(): [
      Icons.directions_car,
      Icons.local_gas_station,
      Icons.build,
      Icons.local_parking,
      Icons.directions_bus,
      Icons.train,
      Icons.flight,
      Icons.local_taxi,
      Icons.two_wheeler,
      Icons.directions_boat,
    ],
    'icons_home'.tr(): [
      Icons.home,
      Icons.water_drop,
      Icons.electric_bolt,
      Icons.wifi,
      Icons.phone_android,
      Icons.tv,
      Icons.cleaning_services,
      Icons.lightbulb,
      Icons.router,
      Icons.weekend,
    ],
    'icons_shopping'.tr(): [
      Icons.checkroom,
      Icons.devices,
      Icons.headphones,
      Icons.watch,
      Icons.chair,
      Icons.local_mall,
      Icons.card_giftcard,
      Icons.local_shipping,
      Icons.smartphone,
      Icons.laptop_mac,
    ],
    'icons_health'.tr(): [
      Icons.medical_services,
      Icons.fitness_center,
      Icons.spa,
      Icons.self_improvement,
      Icons.medication,
      Icons.local_hospital,
      Icons.face,
      Icons.content_cut,
      Icons.favorite,
      Icons.healing,
    ],
    'icons_entertainment'.tr(): [
      Icons.theater_comedy,
      Icons.movie,
      Icons.music_note,
      Icons.videogame_asset,
      Icons.sports_esports,
      Icons.menu_book,
      Icons.palette,
      Icons.camera_alt,
      Icons.pool,
      Icons.subscriptions,
    ],
    'icons_subscriptions'.tr(): [
      Icons.play_circle_outline,
      Icons.music_note,
      Icons.cloud_queue,
      Icons.videogame_asset,
      Icons.fitness_center,
      Icons.language,
      Icons.shopping_bag,
      Icons.article,
      Icons.phone_iphone,
      Icons.security,
      Icons.ondemand_video,
    ],
    'icons_family'.tr(): [
      Icons.pets,
      Icons.child_friendly,
      Icons.school,
      Icons.groups,
      Icons.person,
      Icons.accessibility_new,
      Icons.people,
      Icons.stroller,
      Icons.sentiment_satisfied,
      Icons.cruelty_free,
    ],
    'icons_other'.tr(): [
      Icons.public,
      Icons.local_laundry_service,
      Icons.security,
      Icons.work,
      Icons.help_outline,
      Icons.star,
      Icons.folder,
      Icons.push_pin,
      Icons.explore,
      Icons.bookmark,
    ],
  };

  // Метод, який збирає всі іконки в один плоский список (для перевірок)
  static List<IconData> get allIcons =>
      groupedIcons.values.expand((i) => i).toList();
}
